import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";
import { useState } from "react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span>T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <ShowExamples />
          <AddExample />
        </div>
      </main>
    </>
  );
};

export const ShowExamples = () => {
  const examples = api.example.getAll.useQuery();

  if (!examples.data) return <p>Loading...</p>;

  return (
    <div>
      <ul className="divide-y divide-current">
        {examples.data.map((example) => (
          <li key={example.id} className="p-2">
            {example.text}
          </li>
        ))}
      </ul>
    </div>
  );
};

export const AddExample = () => {
  const addExample = api.example.create.useMutation();
  const utils = api.useContext();

  const [text, setText] = useState("");

  return (
    <div>
      <div className="input-group">
        <input
          className="input-bordered input"
          placeholder="name"
          value={text}
          onChange={(event) => setText(event.target.value)}
        />
        <button
          className="btn"
          onClick={() => {
            addExample.mutate(text, {
              onSuccess: () => {
                utils.example.getAll.invalidate();
                setText("");
              },
            });
          }}
          disabled={addExample.isLoading}
        >
          Create
        </button>
        {addExample.isLoading && <p>Saving...</p>}
      </div>
    </div>
  );
};

export default Home;
