import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";
import { useState } from "react";

const Home: NextPage = () => {
	const hello = api.example.hello.useQuery({ text: "from tRPC" });

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className={styles.container}>
					<ShowExamples />
					<AddExample />
				</div>
			</main>
		</>
	);
};

export const ShowExamples = () => {
	const examples = api.example.getAll.useQuery();

	if (!examples.data) return <p>Loading...</p>;

	return (
		<div>
			<ul>
				{examples.data.map((example) => (
					<li key={example.id}>{example.text}</li>
				))}
			</ul>
		</div>
	);
};

export const AddExample = () => {
	const addExample = api.example.create.useMutation();
	const utils = api.useContext();

	const [text, setText] = useState("");

	return (
		<div>
			<input
				placeholder="name"
				value={text}
				onChange={(event) => setText(event.target.value)}
			/>
			<button
				onClick={() => {
					addExample.mutate(text, {
						onSuccess: () => {
							utils.example.getAll.invalidate();
							setText("");
						},
					});
				}}
				disabled={addExample.isLoading}
			>
				Create
			</button>
			{addExample.isLoading && <p>Saving...</p>}
		</div>
	);
};

export default Home;
